/* =====================================================================
   Test harness.

   The suites load the REAL app from apps/, not a copy. Only two files
   are substituted:

     config.js           -> test/fixtures/config.js        (points nowhere)
     vendor/supabase.js  -> test/fixtures/mock-supabase.js (in-memory)

   Everything else — index.html, app.js, supabase.js, logo.js,
   changelog.js, styles.css — is the exact file that gets deployed.

   The earlier version of this repository tested a sed-rewritten copy of
   app.js. That copy had to be regenerated by hand after every change,
   and a suite passing against a stale copy is worse than no suite at
   all: it reports green while the deployed code is untested. Resolving
   through this file removes the copy, so there is nothing to drift.

   SCRIPTS ARE RUN AS <script> ELEMENTS, NOT THROUGH eval().

   This matters more than it looks. `const` at the top level of a classic
   script goes into the global lexical scope and clashes with an existing
   `var` of the same name; inside eval() it is scoped to the eval call and
   cannot clash. app.js shipped with exactly that collision — the
   vendored bundle declares a global `var supabase` and app.js declared a
   `const supabase` — and the browser refused to parse the entire file:

     Uncaught SyntaxError: Identifier 'supabase' has already been declared

   Every suite passed, because eval() gave the file a scope the browser
   never would. Injecting real script elements reproduces browser scoping,
   so that class of fault is now caught here instead of on a live site.
   ===================================================================== */
const path = require('path');
const fs   = require('fs');
const { JSDOM } = require('jsdom');

const REPO = path.join(__dirname, '..');

const SUBSTITUTIONS = {
  'config.js':          path.join(REPO, 'test', 'fixtures', 'config.js'),
  'vendor/supabase.js': path.join(REPO, 'test', 'fixtures', 'mock-supabase.js')
};

/* resolve('index.html')         -> apps/<app>/index.html
   resolve('vendor/supabase.js') -> test/fixtures/mock-supabase.js */
function resolver(app) {
  return function resolve(rel) {
    const key = rel.replace(/\\/g, '/').split('?')[0];
    if (SUBSTITUTIONS[key]) return SUBSTITUTIONS[key];
    return path.join(REPO, 'apps', app, key);
  };
}

/**
 * Boots one app in jsdom and returns { dom, window, $, sleep }.
 *
 * Scripts are read from disk and evaluated in document order, exactly as
 * the browser would, so a mistake in the load order in index.html shows
 * up here rather than in production.
 */
async function loadApp(app, opts) {
  opts = opts || {};
  const resolve = resolver(app);
  const html = fs.readFileSync(resolve('index.html'), 'utf8');

  /* 'dangerously' is required for injected <script> elements to execute at
     all. jsdom does not fetch the external src attributes in index.html
     because no resource loader is configured, so those tags are inert and
     the files below are what actually run — read from disk, in document
     order, through the resolver. */
  const dom = new JSDOM(html, {
    url: opts.url || 'https://qgrid-mvs.test/',
    pretendToBeVisual: true,
    runScripts: 'dangerously',
    resources: undefined
  });
  const w = dom.window;

  // jsdom leaves a few browser globals out; the app expects them.
  if (!w.structuredClone) w.structuredClone = v => JSON.parse(JSON.stringify(v));
  w.confirm = opts.confirm || (() => true);
  w.alert   = () => {};
  w.scrollTo = () => {};

  const srcs = Array.from(w.document.querySelectorAll('script[src]'))
    .map(s => s.getAttribute('src'));

  const scriptErrors = [];
  w.addEventListener('error', e => scriptErrors.push(e.message || String(e.error)));

  for (const src of srcs) {
    const file = resolve(src);
    if (!fs.existsSync(file)) throw new Error(`index.html references a missing file: ${src}`);
    runScript(w, fs.readFileSync(file, 'utf8'), src);
    /* Hook after the mock client is in place but before app.js runs, so a
       suite can set division settings, seed rows or stub a method and have
       the app boot against them. Mutating them afterwards is no use: the
       app reads settings once during boot, and not every view has a
       refresh button to force a reload. */
    if (src.replace(/\\/g, '/').split('?')[0] === 'vendor/supabase.js' && opts.afterMock) {
      opts.afterMock(w);
    }
  }
  if (scriptErrors.length) throw new Error(scriptErrors.join('; '));

  const sleep = ms => new Promise(r => setTimeout(r, ms));
  await sleep(opts.settle || 300);

  return { dom, window: w, $: id => w.document.getElementById(id), sleep, srcs, scriptErrors };
}

/**
 * Executes source in the window the way a browser would: as a classic
 * <script> element, with top-level declarations landing in the global
 * scope. Never use eval() for this — see the note at the top of the file.
 * A parse error surfaces on window 'error' rather than as a throw, so the
 * caller checks scriptErrors.
 */
function runScript(w, source, label) {
  const el = w.document.createElement('script');
  el.textContent = source;
  el.setAttribute('data-test-src', label || '');
  w.document.head.appendChild(el);
}

/* Tiny assertion helper. Each suite prints one line per check and a
   count on the last line, which run-all-tests.sh reads. */
function suite(name) {
  let pass = 0, fail = 0;
  console.log(`\n${name}`);
  return {
    check(label, cond, extra) {
      if (cond) { pass++; console.log('  ok   ' + label); }
      else { fail++; console.log('  FAIL ' + label + (extra ? ' — ' + extra : '')); }
    },
    group(label) { console.log('\n— ' + label + ' —'); },
    done() {
      console.log(`\n${pass}/${pass + fail} passed`);
      process.exit(fail ? 1 : 0);
    }
  };
}

module.exports = { resolver, loadApp, suite, runScript, REPO };
