/* =====================================================================
   Test harness.

   The suites load the REAL app from apps/, not a copy. Only two files
   are substituted:

     config.js           -> test/fixtures/config.js        (points nowhere)
     vendor/supabase.js  -> test/fixtures/mock-supabase.js (in-memory)

   Everything else — index.html, app.js, supabase.js, logo.js,
   changelog.js, styles.css — is the exact file that gets deployed.

   The earlier version of this repository tested a sed-rewritten copy of
   app.js. That copy had to be regenerated by hand after every change,
   and a suite passing against a stale copy is worse than no suite at
   all: it reports green while the deployed code is untested. Resolving
   through this file removes the copy, so there is nothing to drift.
   ===================================================================== */
const path = require('path');
const fs   = require('fs');
const { JSDOM } = require('jsdom');

const REPO = path.join(__dirname, '..');

const SUBSTITUTIONS = {
  'config.js':          path.join(REPO, 'test', 'fixtures', 'config.js'),
  'vendor/supabase.js': path.join(REPO, 'test', 'fixtures', 'mock-supabase.js')
};

/* resolve('index.html')         -> apps/<app>/index.html
   resolve('vendor/supabase.js') -> test/fixtures/mock-supabase.js */
function resolver(app) {
  return function resolve(rel) {
    const key = rel.replace(/\\/g, '/').split('?')[0];
    if (SUBSTITUTIONS[key]) return SUBSTITUTIONS[key];
    return path.join(REPO, 'apps', app, key);
  };
}

/**
 * Boots one app in jsdom and returns { dom, window, $, sleep }.
 *
 * Scripts are read from disk and evaluated in document order, exactly as
 * the browser would, so a mistake in the load order in index.html shows
 * up here rather than in production.
 */
async function loadApp(app, opts) {
  opts = opts || {};
  const resolve = resolver(app);
  const html = fs.readFileSync(resolve('index.html'), 'utf8');

  const dom = new JSDOM(html, {
    url: opts.url || 'https://qgrid-mvs.test/',
    pretendToBeVisual: true,
    runScripts: 'outside-only'
  });
  const w = dom.window;

  // jsdom leaves a few browser globals out; the app expects them.
  if (!w.structuredClone) w.structuredClone = v => JSON.parse(JSON.stringify(v));
  w.confirm = opts.confirm || (() => true);
  w.alert   = () => {};
  w.scrollTo = () => {};

  const srcs = Array.from(w.document.querySelectorAll('script[src]'))
    .map(s => s.getAttribute('src'));

  for (const src of srcs) {
    const file = resolve(src);
    if (!fs.existsSync(file)) throw new Error(`index.html references a missing file: ${src}`);
    try {
      w.eval(fs.readFileSync(file, 'utf8'));
    } catch (e) {
      throw new Error(`${src} threw while loading: ${e.message}`);
    }
  }

  const sleep = ms => new Promise(r => setTimeout(r, ms));
  await sleep(opts.settle || 300);

  return { dom, window: w, $: id => w.document.getElementById(id), sleep, srcs };
}

/* Tiny assertion helper. Each suite prints one line per check and a
   count on the last line, which run-all-tests.sh reads. */
function suite(name) {
  let pass = 0, fail = 0;
  console.log(`\n${name}`);
  return {
    check(label, cond, extra) {
      if (cond) { pass++; console.log('  ok   ' + label); }
      else { fail++; console.log('  FAIL ' + label + (extra ? ' — ' + extra : '')); }
    },
    group(label) { console.log('\n— ' + label + ' —'); },
    done() {
      console.log(`\n${pass}/${pass + fail} passed`);
      process.exit(fail ? 1 : 0);
    }
  };
}

module.exports = { resolver, loadApp, suite, REPO };
