/* =====================================================================
   Test harness.

   The suites load the REAL app from apps/, not a copy. Only two files
   are substituted:

     config.js           -> test/fixtures/config.js        (points nowhere)
     vendor/supabase.js  -> test/fixtures/mock-supabase.js (in-memory)

   Everything else — index.html, app.js, supabase.js, logo.js,
   changelog.js, styles.css — is the exact file that gets deployed.

   The earlier version of this repository tested a sed-rewritten copy of
   app.js. That copy had to be regenerated by hand after every change,
   and a suite passing against a stale copy is worse than no suite at
   all: it reports green while the deployed code is untested. Resolving
   through this file removes the copy, so there is nothing to drift.

   SCRIPTS ARE RUN AS <script> ELEMENTS, NOT THROUGH eval().

   This matters more than it looks. `const` at the top level of a classic
   script goes into the global lexical scope and clashes with an existing
   `var` of the same name; inside eval() it is scoped to the eval call and
   cannot clash. app.js shipped with exactly that collision — the
   vendored bundle declares a global `var supabase` and app.js declared a
   `const supabase` — and the browser refused to parse the entire file:

     Uncaught SyntaxError: Identifier 'supabase' has already been declared

   Every suite passed, because eval() gave the file a scope the browser
   never would. Injecting real script elements reproduces browser scoping,
   so that class of fault is now caught here instead of on a live site.
   ===================================================================== */
const path = require('path');
const fs   = require('fs');
const { JSDOM } = require('jsdom');

const REPO = path.join(__dirname, '..');

const SUBSTITUTIONS = {
  'config.js':          path.join(REPO, 'test', 'fixtures', 'config.js'),
  'vendor/supabase.js': path.join(REPO, 'test', 'fixtures', 'mock-supabase.js')
};

/* resolve('index.html')         -> apps/<app>/index.html
   resolve('vendor/supabase.js') -> test/fixtures/mock-supabase.js */
function resolver(app) {
  return function resolve(rel) {
    const key = rel.replace(/\\/g, '/').split('?')[0];
    if (SUBSTITUTIONS[key]) return SUBSTITUTIONS[key];
    return path.join(REPO, 'apps', app, key);
  };
}

/**
 * Boots one app in jsdom and returns { dom, window, $, sleep }.
 *
 * Scripts are read from disk and evaluated in document order, exactly as
 * the browser would, so a mistake in the load order in index.html shows
 * up here rather than in production.
 */
async function loadApp(app, opts) {
  opts = opts || {};
  const resolve = resolver(app);
  const html = fs.readFileSync(resolve('index.html'), 'utf8');

  /* 'dangerously' is required for injected <script> elements to execute at
     all. jsdom does not fetch the external src attributes in index.html
     because no resource loader is configured, so those tags are inert and
     the files below are what actually run — read from disk, in document
     order, through the resolver. */
  const dom = new JSDOM(html, {
    url: opts.url || 'https://qgrid-mvs.test/',
    pretendToBeVisual: true,
    runScripts: 'dangerously',
    resources: undefined
  });
  const w = dom.window;

  // jsdom leaves a few browser globals out; the app expects them.
  if (!w.structuredClone) w.structuredClone = v => JSON.parse(JSON.stringify(v));
  /* jsdom implements none of these. confirm() in particular gates every
     destructive action in the app, so without it a suite silently exercises
     nothing past the first prompt. */
  w.confirm = opts.confirm || (() => true);
  w.alert = () => {};
  w.scrollTo = () => {};

  /* jsdom has no canvas and no real image decoding, so photo resizing cannot
     run as written. Stub the three pieces it uses — Image, canvas.toBlob and
     object URLs — so the UPLOAD PATH is exercised even though the pixels are
     not. Without this the photo flow would be untestable, which is how it
     shipped broken the first time. */
  /* A FileList that behaves like the real one: LIVE, and emptied when the
     input's value is reset. The suites used to attach a plain array, which
     survives a reset — so the app could read files AFTER clearing value, get
     nothing, and skip the upload, while every test passed. That exact bug
     shipped and took four attempts to find. A test double gentler than the
     platform hides the faults worth catching.

     Use it as: setFiles(inputEl, [{name, size}]). */
  w.__setFiles = (el, arr) => {
    /* ONE object, mutated in place — that is what makes a FileList "live".
       Returning a fresh copy per read (the first attempt at this) let a
       snapshot survive the reset, so the suite still passed against the bug.
       The real platform hands back the same object and empties it. */
    const fl = { item: i => fl[i] };
    let n = arr.length;
    arr.forEach((f, i) => { fl[i] = f; });
    Object.defineProperty(fl, 'length', { get: () => n });

    Object.defineProperty(el, 'files', { configurable: true, get: () => fl });
    let val = arr.length ? 'C:\\fakepath\\' + arr[0].name : '';
    Object.defineProperty(el, 'value', {
      configurable: true,
      get: () => val,
      set: v => {
        val = v;
        if (v === '') { for (let i = 0; i < n; i++) delete fl[i]; n = 0; }
      }
    });
  };

  /* jsdom has no PointerEvent. The app listens for pointer events so a
     finger, a stylus and a mouse behave identically; without a constructor
     the signature pad cannot be driven from a test at all. */
  if (!w.PointerEvent) {
    w.PointerEvent = class extends w.Event {
      constructor(type, init = {}) {
        super(type, init);
        this.clientX = init.clientX || 0;
        this.clientY = init.clientY || 0;
        this.pointerId = init.pointerId || 1;
      }
    };
  }
  /* Drive a signature stroke the way a finger would. */
  w.__sign = (canvas, points) => {
    canvas.dispatchEvent(new w.PointerEvent('pointerdown',
      { bubbles: true, clientX: points[0][0], clientY: points[0][1] }));
    for (const [x, y] of points.slice(1)) {
      w.dispatchEvent(new w.PointerEvent('pointermove', { clientX: x, clientY: y }));
    }
    w.dispatchEvent(new w.PointerEvent('pointerup', {}));
  };

  w.URL.createObjectURL = () => 'blob:test/photo';
  w.URL.revokeObjectURL = () => {};
  class FakeImage {
    constructor() { this.width = 3000; this.height = 2000; }
    set src(v) { setTimeout(() => this.onload && this.onload(), 0); }
    get src() { return 'blob:test/photo'; }
  }
  w.Image = FakeImage;
  /* Patch the PROTOTYPE, not just createElement. The signature pad arrives
     through innerHTML, so it is a real jsdom HTMLCanvasElement with no 2d
     context at all — stubbing createElement alone left it untestable, which
     is how the field shipped as a placeholder for eleven versions. */
  w.HTMLCanvasElement.prototype.getContext = function () {
    return {
      drawImage() {}, clearRect() {}, beginPath() {}, moveTo() {}, lineTo() {},
      stroke() {}, fillRect() {}, closePath() {}, save() {}, restore() {},
      set lineWidth(v) {}, set lineCap(v) {}, set lineJoin(v) {}, set strokeStyle(v) {},
      set fillStyle(v) {}
    };
  };
  w.HTMLCanvasElement.prototype.toBlob = function (cb, type) {
    cb({ size: type === 'image/png' ? 4200 : 240000, type: type || 'image/jpeg' });
  };
  w.HTMLCanvasElement.prototype.getBoundingClientRect = function () {
    return { left: 0, top: 0, width: 640, height: 200, right: 640, bottom: 200 };
  };

  const srcs = Array.from(w.document.querySelectorAll('script[src]'))
    .map(s => s.getAttribute('src'));

  const scriptErrors = [];
  w.addEventListener('error', e => scriptErrors.push(e.message || String(e.error)));

  for (const src of srcs) {
    const file = resolve(src);
    if (!fs.existsSync(file)) throw new Error(`index.html references a missing file: ${src}`);
    runScript(w, fs.readFileSync(file, 'utf8'), src);
    /* Hook after the mock client is in place but before app.js runs, so a
       suite can set division settings, seed rows or stub a method and have
       the app boot against them. Mutating them afterwards is no use: the
       app reads settings once during boot, and not every view has a
       refresh button to force a reload. */
    if (src.replace(/\\/g, '/').split('?')[0] === 'vendor/supabase.js' && opts.afterMock) {
      opts.afterMock(w);
    }
  }
  if (scriptErrors.length) throw new Error(scriptErrors.join('; '));

  const sleep = ms => new Promise(r => setTimeout(r, ms));
  await sleep(opts.settle || 300);

  return { dom, window: w, $: id => w.document.getElementById(id), sleep, srcs, scriptErrors };
}

/**
 * Executes source in the window the way a browser would: as a classic
 * <script> element, with top-level declarations landing in the global
 * scope. Never use eval() for this — see the note at the top of the file.
 * A parse error surfaces on window 'error' rather than as a throw, so the
 * caller checks scriptErrors.
 */
function runScript(w, source, label) {
  const el = w.document.createElement('script');
  el.textContent = source;
  el.setAttribute('data-test-src', label || '');
  w.document.head.appendChild(el);
}

/* Tiny assertion helper. Each suite prints one line per check and a
   count on the last line, which run-all-tests.sh reads. */
function suite(name) {
  let pass = 0, fail = 0;
  console.log(`\n${name}`);
  return {
    check(label, cond, extra) {
      if (cond) { pass++; console.log('  ok   ' + label); }
      else { fail++; console.log('  FAIL ' + label + (extra ? ' — ' + extra : '')); }
    },
    group(label) { console.log('\n— ' + label + ' —'); },
    done() {
      console.log(`\n${pass}/${pass + fail} passed`);
      process.exit(fail ? 1 : 0);
    }
  };
}

module.exports = { resolver, loadApp, suite, runScript, REPO };
