/**
 * Rebuilds db/schema-complete.sql from the numbered migrations.
 *
 *   node scripts/build-schema.mjs
 *   node scripts/build-schema.mjs --check     (exit 1 if stale)
 *
 * WHY THIS EXISTS.
 *
 * schema-complete.sql is the one-file script pasted into the Supabase SQL
 * editor when standing up a division. It was written by hand, and it went
 * stale the moment 003 and 004 were added — worse, its ledger stamp still
 * claimed only 001 and 002 were applied, so a division provisioned from it
 * would be missing two migrations AND report itself up to date. The drift
 * check would have agreed with it.
 *
 * So it is generated now, and test-integrity.js fails if the checked-in
 * copy does not match what this produces.
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";

const OUT = "db/schema-complete.sql";
const migrations = readdirSync("db").filter(f => /^\d{3}-.*\.sql$/.test(f)).sort();
if (!migrations.length) { console.error("No migrations found in db/"); process.exit(1); }

const strip = src => {
  // Drop the file's own banner comment; the section header replaces it.
  const i = src.indexOf("\n\n");
  return (i > 0 && src.slice(0, i).trim().startsWith("--")) ? src.slice(i + 2) : src;
};
const section = (n, title, body) =>
  `\n\n-- ============================================================\n` +
  `--  SECTION ${n} — ${title}\n` +
  `-- ============================================================\n\n${body.trim()}\n`;

let n = 0;
let out = `-- ============================================================
--  ACTOM Grid — Inspections
--  COMPLETE SCHEMA — one runnable script
--
--  GENERATED by scripts/build-schema.mjs. Do not edit by hand: add a
--  numbered migration in db/ and run that script again. An earlier
--  hand-maintained version of this file silently stopped at 002 while
--  claiming to be complete, which would have left a new division two
--  migrations behind and reporting itself up to date.
--
--  Paste into the Supabase SQL editor of a NEW, EMPTY project and run.
--  Order matters; do not run sections out of sequence.
--
--  Built from: ${migrations.join(", ")}
--
--  This script is for a fresh project. It is not idempotent: running it
--  twice will fail on "type user_role already exists", which is the
--  intended safety net rather than a bug.
-- ============================================================

-- Refuse to run against a database that already has Grid in it.
do $guard$
begin
  if exists (select 1 from information_schema.tables
              where table_schema = 'public' and table_name = 'inspections') then
    raise exception 'Grid schema already present. Use scripts/migrate.mjs for changes, not this script.';
  end if;
end $guard$;
`;

for (const f of migrations) {
  out += section(++n, f, strip(readFileSync(`db/${f}`, "utf8")));
}
out += section(++n, "Group reference data", strip(readFileSync("db/seed.sql", "utf8")));
out += section(++n, "Division seed — EDIT BEFORE RUNNING",
               strip(readFileSync("db/seed-division-mvs.sql", "utf8")));

out += `

-- ============================================================
--  SECTION ${++n} — Migration ledger stamp
--
--  Running this script bypasses scripts/migrate.mjs, so the ledger it
--  reads would be empty and the next run would try to apply everything
--  again. Stamping every migration this script contains keeps the ledger
--  honest and keeps verify-drift.mjs meaningful.
-- ============================================================

create table if not exists public.qgrid_migrations (
  filename   text primary key,
  applied_at timestamptz not null default now()
);
alter table public.qgrid_migrations enable row level security;
revoke all on public.qgrid_migrations from anon, authenticated;

insert into public.qgrid_migrations (filename) values
${migrations.map(f => `  ('${f}')`).join(",\n")}
on conflict (filename) do nothing;


-- ============================================================
--  SECTION ${++n} — Verification
--  Run these and check the results before going any further.
-- ============================================================

-- Every table must have row level security on. Expect zero rows.
select tablename as "TABLE WITHOUT RLS - FIX BEFORE USE"
  from pg_tables
 where schemaname = 'public' and rowsecurity is false;

-- Every view must be security_invoker, or it bypasses RLS. Expect zero rows.
select c.relname as "VIEW BYPASSING RLS - FIX BEFORE USE"
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
 where n.nspname = 'public' and c.relkind = 'v'
   and coalesce((select option_value from pg_options_to_table(c.reloptions)
                  where option_name = 'security_invoker'), 'false') <> 'true';

-- Reference data loaded.
select 'stages' as item, count(*) as rows from manufacturing_stages
union all select 'departments',  count(*) from departments
union all select 'defect codes', count(*) from defect_codes
union all select 'families',     count(*) from product_families
union all select 'equipment',    count(*) from equipment
union all select 'requirements', count(*) from inspection_requirements
order by item;

-- Controls present. Expect all six.
select tgname as trigger_installed from pg_trigger
 where tgname in ('trg_inspection_lock','trg_result_lock','trg_equipment_block',
                  'trg_signature_competency','trg_inspection_ref','on_auth_user_created')
 order by tgname;

-- Functions the app calls. Expect three.
select proname as rpc_available from pg_proc
 where proname in ('submit_inspection','publish_template_revision','generate_inspections')
 order by proname;

-- Division settings, both defaulting off.
select code, name, hold_points, require_second_approver from division_profile;

-- Numbering works. Expect INS-26-0001 then INS-26-0002.
select next_ref('INS') as first_ref, next_ref('INS') as second_ref;
delete from ref_sequences where prefix = 'INS';   -- reset so live records start at 1


-- ============================================================
--  NEXT STEP
--
--  Sign in once through Microsoft. That creates your profile row as
--  INACTIVE with no role, and nobody can activate it because there is no
--  administrator yet. Break the loop once, by hand:
--
--    update profiles
--       set role = 'sysadmin', active = true
--     where email = 'you@actom.co.za';
--
--  Everything after that happens in Administration > Users & roles.
-- ============================================================
`;

if (process.argv.includes("--check")) {
  let current = "";
  try { current = readFileSync(OUT, "utf8"); } catch {}
  if (current !== out) {
    console.error(`${OUT} is stale. Run: node scripts/build-schema.mjs`);
    process.exit(1);
  }
  console.log(`${OUT} is up to date (${migrations.length} migrations).`);
} else {
  writeFileSync(OUT, out);
  console.log(`${OUT} rebuilt from ${migrations.length} migrations: ${migrations.join(", ")}`);
}
